image: gitpod/workspace-full

tasks:
  - init: pip install -r requirements.txt
    command: jupyter notebook notebooks/intro.ipynb --ip=0.0.0.0 --no-browser --NotebookApp.token='' --NotebookApp.password=''

ports:
  - port: 8888
    onOpen: open-preview